"""Pipeline: a Ray Data-based streaming pipeline framework."""

import asyncio
import json
import logging
import os
from collections.abc import Callable
from datetime import datetime
from pathlib import Path

import pandas as pd
import ray
import ray.data
from ray.data import ActorPoolStrategy, TaskPoolStrategy

from .base import BaseRecipe, Stage
from .utils.data_io import convert_to_python_types
from .utils.framework import FRAMEWORK_FIELDS
from .utils.logging_utils import setup_logging

logger = logging.getLogger(__name__)


def clean_nan_values(item: dict, warn: bool = True) -> dict:
    """
    Clean NaN values in a dict by converting them to None.

    Ray Data uses columnar operations, so all items should share the same fields.
    If some items have unique fields, pandas fills missing values with NaN.

    Args:
        item: item dict to clean
        warn: whether to log a warning when NaN is found

    Returns:
        cleaned dict (NaN -> None)
    """
    import math

    has_nan = False
    cleaned_item = {}

    for k, v in item.items():
        # Check for NaN (including pandas NaN and numpy nan).
        if isinstance(v, float) and math.isnan(v):
            if warn and not has_nan:
                # Warn once per item when NaN is first seen.
                logger.warning(
                    "Found NaN value in item %s. This should not happen after framework initialization. "
                    "Please report this as a bug if you see this message.",
                    item.get("id", "unknown"),
                )
                has_nan = True
            cleaned_item[k] = None
        else:
            cleaned_item[k] = v

    return cleaned_item


def safe_str(value, max_length: int = 500) -> str:
    """
    Safely convert a value to string to avoid huge prints.

    Args:
        value: value to convert
        max_length: max string length

    Returns:
        safe string representation
    """
    try:
        v_str = str(value)
        if len(v_str) > max_length:
            return v_str[:max_length] + f"... (truncated, total {len(v_str)} chars)"
        return v_str
    except Exception as e:
        return f"<error converting to string: {e}>"


def safe_repr_item(item: dict, max_value_length: int = 200) -> str:
    """
    Build a safe string representation of an item to avoid huge prints.

    Args:
        item: item dict to represent
        max_value_length: max length per field value

    Returns:
        safe string representation
    """
    result = []
    for k, v in item.items():
        v_str = safe_str(v, max_value_length)
        result.append(f"  {k}: {v_str}")
    return "{\n" + "\n".join(result) + "\n}"


class Pipeline:
    """
    Pipeline framework built on Ray Data.

    Features:
    - streaming data processing
    - concurrency control (batch_size * concurrency)
    - order preservation (preserve_order, enabled by default)
    - backpressure (built into Ray Data)
    - resume support (skip already processed items)
    - actor mode: each worker initializes once (good for API clients, vLLM, etc.)

    Usage:
        pipeline = Pipeline(
            recipe=SFTRecipe(config),
            batch_size=32,
            concurrency=2,
        )
        pipeline.run("data/input.jsonl", "output/train.jsonl")
    """

    def __init__(
        self,
        recipe: BaseRecipe,
        batch_size: int = 32,
        concurrency: int = 2,
        stage_concurrency: dict[str, int] = None,
        work_dir: str = None,
        preserve_order: bool = True,
        resume: bool = True,
        flush_interval: int = 10,
    ):
        """
        Initialize a Pipeline.

        Args:
            recipe: recipe instance
            batch_size: items per batch (smallest processing unit)
            concurrency: pipeline parallelism (batch_size * concurrency overall)
            stage_concurrency: per-stage override by class name, e.g. {"SamplerStage": 100}
            work_dir: work directory for intermediate results (auto-generated by default)
            preserve_order: keep item order; True by default. Disable for more speed.
            resume: enable resume; skips items already in the output file. Uses a
                content hash of "messages" to compute _resume_id for de-duplication.
                If disabled, ensure the output file is empty to avoid duplicates.
            flush_interval: flush every N successful items
        """
        self.recipe = recipe
        self.batch_size = batch_size
        self.concurrency = concurrency
        self.stage_concurrency = stage_concurrency or {}
        self.work_dir = Path(work_dir) if work_dir else self._auto_work_dir()
        self.preserve_order = preserve_order
        self.resume = resume
        self.flush_interval = flush_interval

        self._stages = recipe.stages()

        # Validate stage_concurrency config.
        self._validate_stage_concurrency()

    def _auto_work_dir(self) -> Path:
        """Auto-generate a work directory."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        return Path("output") / timestamp

    def _validate_stage_concurrency(self):
        """
        Validate stage_concurrency config.

        Ensures configured stage names are valid to catch config mistakes early.
        """
        if not self.stage_concurrency:
            return

        valid_stage_names = {type(stage).__name__ for stage in self._stages}
        invalid_names = set(self.stage_concurrency.keys()) - valid_stage_names

        if invalid_names:
            raise ValueError(
                f"Invalid stage names in stage_concurrency: {invalid_names}. "
                f"Valid stage names are: {valid_stage_names}"
            )

    def _compute_resume_id(self, item: dict) -> str:
        """
        Compute the resume ID for an item.

        Uses a deterministic hash of the content (default: messages field).
        Internal implementation detail.

        Args:
            item: item dict

        Returns:
            16-character hash string (non-empty)

        Note:
            If None or empty, Pipeline raises in add_resume_id.
        """
        import hashlib

        # Use messages field if present.
        messages = item.get("messages", [])
        if messages:
            # Convert to native Python types (numpy/pandas).
            messages = convert_to_python_types(messages)
            content = json.dumps(messages, sort_keys=True, ensure_ascii=False)
        else:
            # Otherwise hash the whole item.
            content = json.dumps(item, sort_keys=True, ensure_ascii=False)

        hash_obj = hashlib.sha256(content.encode("utf-8"))
        return hash_obj.hexdigest()[:16]

    def _load_processed_ids(self, output_path: str) -> set:
        """
        Load processed IDs from the output file.

        Used for resume: skip already processed items. Uses _resume_id.

        Note: all IDs are loaded into memory.
        """
        processed_ids = set()
        if os.path.exists(output_path):
            with open(output_path) as f:
                for line in f:
                    if line.strip():
                        try:
                            item = json.loads(line)
                            resume_id = item.get("_resume_id")
                            if resume_id is not None:
                                processed_ids.add(resume_id)
                        except json.JSONDecodeError:
                            continue

            if len(processed_ids) > 1_000_000:
                logger.warning(
                    "[Pipeline] Loaded %s processed IDs into memory.",
                    f"{len(processed_ids):,}",
                )

        return processed_ids

    def _add_framework_fields(self, batch):
        """
        Add framework fields to each item.

        Framework fields:
        - _resume_id: content-hash ID (used for resume)
        - _failed: whether the item failed (initially None)
        - _error: error message (initially None)
        - _traceback: error traceback (initially None)

        All items get these fields to avoid pandas filling NaN.
        """
        # Convert to DataFrame if needed.
        if isinstance(batch, dict):
            df = pd.DataFrame(batch)
        else:
            df = batch

        if df.empty:
            return df

        # Compute resume_id for each row.
        resume_ids = []
        for idx, row in df.iterrows():
            row_dict = row.to_dict()
            resume_id = self._compute_resume_id(row_dict)

            # Validate resume_id.
            if resume_id is None or resume_id == "":
                item_id = row_dict.get("id", "unknown")
                error_msg = (
                    f"❌ Failed to compute _resume_id for item (id={item_id}, row_index={idx})\n"
                    f"   resume_id is None or empty. This usually indicates:\n"
                    f"   1. The data item is completely empty or malformed\n"
                    f"   2. The 'messages' field is missing or invalid\n"
                    f"   Data sample: {str(row_dict)[:200]}..."
                )
                raise ValueError(error_msg)

            resume_ids.append(resume_id)

        # Add framework fields (initialized to None for schema consistency).
        df["_resume_id"] = resume_ids
        df["_failed"] = None
        df["_error"] = None
        df["_traceback"] = None

        return df

    def _create_filter_processed_fn(self, processed_ids: set):
        """
        Create a function to filter already processed items.

        Args:
            processed_ids: set of processed _resume_id values

        Returns:
            filter function for map_batches
        """

        def filter_processed(batch):
            """Filter out already processed items."""
            # Convert to DataFrame if needed.
            if isinstance(batch, dict):
                df = pd.DataFrame(batch)
            else:
                df = batch

            if df.empty:
                return df

            # Filter using existing _resume_id values.
            mask = ~df["_resume_id"].isin(processed_ids)
            return df[mask]

        return filter_processed

    def run(self, input_path: str, output_path: str = None):
        """
        Run the pipeline.

        Args:
            input_path: input data path (JSONL only)
            output_path: output path (default: work_dir/output.jsonl)

        Raises:
            ValueError: if _resume_id is None or empty
        """
        _, log_path = setup_logging(role="driver")
        logger.info("[Pipeline] Logging to: %s", log_path)

        # Ensure Ray is initialized.
        if not ray.is_initialized():
            ray.init()

        # Set output path.
        if output_path is None:
            self.work_dir.mkdir(parents=True, exist_ok=True)
            output_path = str(self.work_dir / "output.jsonl")
        else:
            Path(output_path).parent.mkdir(parents=True, exist_ok=True)

        # Configure order and progress bars.
        ctx = ray.data.DataContext.get_current()
        ctx.execution_options.preserve_order = self.preserve_order
        ctx.enable_rich_progress_bars = True
        ctx.use_ray_tqdm = False

        # Pipeline optimization: show detailed progress.
        ctx.execution_options.verbose_progress = True

        # Load processed IDs (resume).
        processed_ids = set()
        if self.resume:
            processed_ids = self._load_processed_ids(output_path)
            if processed_ids:
                logger.info(
                    "[Resume] Found %s processed items, will skip them.", len(processed_ids)
                )

        # Read JSONL data (one JSON object per line).
        ds = ray.data.read_json(input_path, lines=True)

        # Add framework fields (resume + error handling).
        ds = ds.map_batches(
            self._add_framework_fields,
            batch_format="pandas",
            batch_size=self.batch_size,
            compute=TaskPoolStrategy(size=self.concurrency),
        )

        # Filter already processed items (resume).
        if processed_ids:
            ds = ds.map_batches(
                self._create_filter_processed_fn(processed_ids),
                batch_format="pandas",
                batch_size=self.batch_size,
                compute=TaskPoolStrategy(size=self.concurrency),
            )

        # Apply each stage (actor mode: initialize once per worker).
        for stage in self._stages:
            concurrency = self._get_stage_concurrency(stage)
            ds = ds.map_batches(
                self._create_map_batches_fn(stage),
                batch_format="pandas",
                batch_size=self.batch_size,
                compute=ActorPoolStrategy(size=concurrency),
            )

        # Write output.
        self._write_output(ds, output_path, len(processed_ids))

    def _write_output(self, ds, output_path: str, resume_count: int):
        """
        Write output data (append mode, supports resume).

        Args:
            ds: Ray Dataset
            output_path: output file path
            resume_count: number of resumed (skipped) items
        """
        total_rows = 0
        success_rows = 0
        failed_rows = 0

        with open(output_path, "a") as f:
            try:
                for row in ds.iter_rows():
                    item = dict(row)
                    total_rows += 1

                    # pandas may introduce NaN values.
                    item = clean_nan_values(item, warn=True)

                    # Count failed items but keep them in the output.
                    if item.get("_failed") is True:
                        failed_rows += 1
                        error_msg = safe_str(
                            item.get("_error") or "Unknown error", max_length=10000
                        )
                        item_id = safe_str(item.get("id", "unknown"), max_length=100)
                        resume_id = safe_str(item.get("_resume_id", "unknown"), max_length=100)
                        traceback_msg = safe_str(
                            item.get("_traceback", "unknown"), max_length=10000
                        )
                        logger.warning(
                            "[Pipeline] Writing failed item to output | ID=%s | Resume ID=%s | Error=%s | Traceback=%s",
                            item_id,
                            resume_id,
                            error_msg,
                            traceback_msg,
                        )
                    else:
                        success_rows += 1

                    # Write all items.
                    f.write(json.dumps(item, ensure_ascii=False) + "\n")

                    # Flush periodically to ensure data is written.
                    if success_rows % self.flush_interval == 0:
                        f.flush()
                        os.fsync(f.fileno())
            except Exception as e:
                import traceback

                error_trace = traceback.format_exc()
                logger.error(
                    "[Pipeline] Error writing to output file: %s | Traceback: %s | Item: %s",
                    safe_str(e, max_length=200),
                    safe_str(error_trace, max_length=2000),
                    safe_repr_item(item),
                )
            finally:
                # Final flush to ensure all data is written.
                f.flush()
                os.fsync(f.fileno())

        summary = (
            "[Pipeline Summary]\n"
            f"  Resume items:  {resume_count}\n"
            f"  New items:     {total_rows}\n"
            f"  Success:       {success_rows}\n"
            f"  Failed:        {failed_rows}\n"
            f"  Output file:   {output_path}\n"
            f"[Done] Output written to: {output_path}"
        )
        logger.info(summary)

    def _get_stage_concurrency(self, stage: Stage) -> int:
        """
        Get concurrency for a stage.

        Prefer stage_concurrency override, otherwise use default concurrency.
        """
        stage_name = type(stage).__name__
        return self.stage_concurrency.get(stage_name, self.concurrency)

    def _create_map_batches_fn(self, stage: Stage) -> Callable:
        """
        Create a map_batches callable for a stage.

        Handles:
        - sync/async process methods
        - skipping failed items
        - exception capture and _failed marking
        """

        class StageCallable:
            """Wrap a Stage as a Ray Data callable."""

            def __init__(self):
                setup_logging(role="worker")
                is_async = stage.is_async()
                # Actor mode: initialize once per worker.
                self._stage = stage
                self._stage.initialize()
                self._is_async = is_async

            def __del__(self):
                if hasattr(self, "_stage"):
                    self._stage.shutdown()

            def __call__(self, batch):
                """Process a batch."""
                # Convert to DataFrame.
                if isinstance(batch, dict):
                    df = pd.DataFrame(batch)
                else:
                    df = batch

                if df.empty:
                    return df

                # Convert to list of dict.
                rows = df.to_dict("records")
                rows = [convert_to_python_types(row) for row in rows]

                # Preserve framework fields per item.
                framework_data = {
                    idx: {k: item.get(k) for k in FRAMEWORK_FIELDS} for idx, item in enumerate(rows)
                }

                try:
                    if self._is_async:
                        results = asyncio.run(self._stage.process(rows))
                    else:
                        results = self._stage.process(rows)

                    # Restore framework fields.
                    for idx, result in enumerate(results):
                        for field, value in framework_data[idx].items():
                            if value is not None and result.get(field) is None:
                                result[field] = value

                except Exception as e:
                    # Stage-level fallback: mark the whole batch as failed.
                    # Normally Stage.process_item() should handle exceptions per item.
                    # Hitting this branch means the stage raised unexpectedly.
                    import traceback

                    error_trace = traceback.format_exc()
                    stage_name = type(self._stage).__name__
                    logger.error(
                        "[%s] Batch processing failed | Error: %s | Traceback: %s",
                        stage_name,
                        safe_str(e, max_length=500),
                        safe_str(error_trace, max_length=2000),
                    )

                    results = [
                        {
                            **item,
                            **framework_data[idx],
                            "_failed": True,
                            "_error": safe_str(f"{stage_name}: {str(e)}", max_length=1000),
                            "_traceback": safe_str(error_trace, max_length=5000),
                        }
                        for idx, item in enumerate(rows)
                    ]

                # Align fields when items have different keys.
                if len(results) > 1:
                    all_keys = [set(item.keys()) for item in results]
                    if not all(keys == all_keys[0] for keys in all_keys):
                        all_fields = set().union(*all_keys)
                        results = [
                            {field: item.get(field) for field in all_fields} for item in results
                        ]

                return pd.DataFrame(results)

        return StageCallable
